TORCH_USE_CUDA_DSA=1 MAMBA_DEBUG=1 CUDA_LAUNCH_BLOCKING=1 TORCH_SHOW_CPP_STACKTRACES=1 TORCH_BACKTRACE=1 MAMBA_FORCE_BUILD=TRUE python setup.py clean --all && \
rm -rf build/ dist/ *.egg-info && \
TORCH_USE_CUDA_DSA=1 MAMBA_DEBUG=1 CUDA_LAUNCH_BLOCKING=1 TORCH_SHOW_CPP_STACKTRACES=1 TORCH_BACKTRACE=1 MAMBA_FORCE_BUILD=TRUE pip install -v --no-build-isolation -e .
